CREATE TABLE "users" (
    "id" VARCHAR(255) PRIMARY KEY,
    "username" VARCHAR UNIQUE NOT NULL,
    "balance" BIGINT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TYPE transaction_type AS ENUM ('WAGER', 'PAYOUT', 'REFUND', 'SIGNUP_BONUS', 'LABOR', 'ADMINS_BLESSING');
CREATE TABLE "transactions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" VARCHAR(255) NOT NULL,
    "amount" BIGINT NOT NULL,
    "type" transaction_type NOT NULL,
    "reference_id" BIGINT,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TYPE game_status AS ENUM ('IN_PROGRESS', 'PLAYER_WON', 'PLAYER_BLACKJACK', 'DEALER_WON', 'PUSH', 'CANCELLED');
CREATE TABLE "games" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" VARCHAR(255) NOT NULL,
    "bet_amount" BIGINT NOT NULL,
    "status" game_status NOT NULL,
    "state" JSONB NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_games_user_status ON "games" ("user_id", "status");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "transactions" ADD FOREIGN KEY ("reference_id") REFERENCES "games" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "games" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;